# This is a basic workflow that is manually triggered

name: Import graphs to eccenca Corporate Memory @ aksw.eccenca.dev

on:
  push:
    branches: [master]

jobs:
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - shell: bash
        env:
          OAUTH_CLIENT_SECRET: ${{ secrets.CMEM_SERVICE_ACCOUNT_CLIENT_SECRET }}
          run: |
            echo "$OAUTH_CLIENT_SECRET"

