
name: Import to eccenca Corporate Memory

on:
  push:
    branches: [master]

jobs:
  graph-import:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.eccenca.com/eccenca-cmemc:v20.12
      volumes:
        - ${{ github.workspace }}:/data
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: cmemc graph import --replace .
        env:
          CMEM_BASE_URI: https://aksw.eccenca.dev
          OAUTH_GRANT_TYPE: client_credentials
          OAUTH_CLIENT_ID: cmem-service-account
          OAUTH_CLIENT_SECRET: ${{ secrets.CMEM_SERVICE_ACCOUNT_CLIENT_SECRET }}
          #run: cmemc graph import --replace .
        run: cmemc graph import --replace .

