# This is a basic workflow that is manually triggered

name: Import graphs to eccenca Corporate Memory @ aksw.eccenca.dev

on:
  push:
    branches: [master]

jobs:
  graph-import:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.eccenca.com/eccenca-cmemc:v20.12
      volumes:
        - ${{ github.workspace }}:/data
      env:
        CMEM_BASE_URI: https://aksw.eccenca.dev
        OAUTH_GRANT_TYPE: client_credentials
        OAUTH_CLIENT_ID: cmem-service-account
        OAUTH_CLIENT_SECRET: ${{ secrets.CMEM_SERVICE_ACCOUNT_CLIENT_SECRET }}
        CMEMC_CONNECTION: aksw.eccenca.dev
    steps:
      - name: cmemc graph list
        uses: docker://docker-registry.eccenca.com/eccenca-cmemc:v20.12
        with:
          entrypoint: /bin/bash
          args: cmemc graph list

