# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches: [ master ]

jobs:
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
