# Trigger Page Build for https://github.com/AKSW/aksw.org.jekyllrdf
name: Trigger Page Build

on:
  push:
    branches: [master]

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - name: Invoke workflow in another repo
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: "Build & Publish to GitHub Pages"
        repo: AKSW/aksw.org.jekyllrdf
        token: ${{ secrets.GH_ACCESS_TOKEN_FOR_TRIGGER }}
