name: Trigger Page Build for https://github.com/AKSW/aksw.org.jekyllrdf

on:
  push:
    branches: [master]

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - name: Invoke workflow in another repo
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build-and-publish-page
        repo: AKSW/aksw.org.jekyllrdf
        token: ${{ secrets.GH_ACCESS_TOKEN_FOR_TRIGGER }}
